<?php
/** @var \Katizon\ProductList\Block\Index\Categories $block */
/** @var \Magento\Framework\Escaper $escaper */

$categories = $block->getCategories();
?>

<?php foreach ($categories->getChildrenData() as $category): ?>
    <ul class="category">
        <li class="category-name">
            <a href="<?= $block->getProductsListUrl($category->getId()) ?>"><?= $escaper->escapeHtmlAttr($category->getName()) ?></a>
        </li>
        <?php foreach ($category->getChildrenData() as $subCategory): ?>
            <ul class="subcategory">
                <li class="subcategory-name">
                    <a href="<?= $block->getProductsListUrl($subCategory->getId()) ?>"><?= $escaper->escapeHtmlAttr($subCategory->getName()) ?></a>
                </li>
            </ul>
        <?php endforeach; ?>
        </li>
    </ul>

<?php endforeach; ?>

